CREATE LIVE TABLE college_geo (
  CONSTRAINT valid_latitude EXPECT (LATITUDE IS NOT NULL AND LATITUDE <> 'NA') ON VIOLATION DROP ROW,
  CONSTRAINT valid_longitude EXPECT (LONGITUDE IS NOT NULL AND LONGITUDE <> 'NA') ON VIOLATION DROP ROW
)
AS
SELECT
  INSTNM,
  CITY,
  STABBR,
  ZIP,
  ST_FIPS,
  REGION,
  LOCALE,
  LOCALE2,
  LATITUDE,
  LONGITUDE
FROM workspace.default.college_scorecard
WHERE school_start_year = '2023';
