CREATE LIVE TABLE college_geo (
  CONSTRAINT valid_latitude EXPECT (LATITUDE IS NOT NULL) ON VIOLATION DROP ROW,
  CONSTRAINT valid_longitude EXPECT (LONGITUDE IS NOT NULL) ON VIOLATION DROP ROW
)
AS
SELECT
  CAST(INSTNM AS STRING) AS INSTNM,
  CAST(CITY AS STRING) AS CITY,
  CAST(STABBR AS STRING) AS STABBR,
  CAST(ZIP AS STRING) AS ZIP,
  CAST(ST_FIPS AS STRING) AS ST_FIPS,
  CAST(REGION AS STRING) AS REGION,
  CAST(LOCALE AS STRING) AS LOCALE,
  CAST(LOCALE2 AS STRING) AS LOCALE2,
  CAST(LATITUDE AS DOUBLE) AS LATITUDE,
  CAST(LONGITUDE AS DOUBLE) AS LONGITUDE
FROM workspace.default.college_scorecard
WHERE school_year_start = '2023';
